### ISSUE TITLE
Exceptions in sending fulfilled transaction over to a bigchaindb node 

### ISSUE THREAD

**Issue by saurabh1002** [bigchaindb/bigchaindb-driver#289]
* bigchaindb-driver version:0.10.1
* Python version:3.5.2
* Operating System:Ubuntu 16.04 Xenial

### Description
I am trying to do the basic setup of bigchaindb and i am following the bigchaindb quickstart guide from docs.bigchaindb.com

### What I Did
(All the previous steps were executed successfully)
sent_creation_tx = bdb.transactions.send(fulfilled_creation_tx)

I got the following exceptions:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/requests/packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.5/dist-packages/requests/packages/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.5/socket.py", line 732, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

**Comment by codegeschrei** [comment]
I'll close this for now. Hopefully you don't have any issues anymore :)
