### ISSUE TITLE
Can't install bigchaindb_driver on my PINE64 through pip3

### ISSUE THREAD

**Issue by wputnam** [bigchaindb/bigchaindb-driver#302]
* bigchaindb-driver version: 0.3.1
* Python version: 3.5.2
* Operating System: Linux pine64 3.10.104 #13 SMP PREEMPT Mon Dec 12 15:00:06 MYT 2016 aarch64 aarch64 aarch64 GNU/Linux
* pip3 version: pip 9.0.1 from /usr/local/lib/python3.5/dist-packages (python 3.5)

### Description

Trying to install the driver through pip3. I had already installed BigChainDB moments before.
An error occurs during installation, and pip3 exits.

### What I Did

This was done with a fresh installation of the OS on a PINE64 PA641GB board.

```
ubuntu@pine64:~$ sudo pip3 install pip setuptools bigchaindb
# installation successful
ubuntu@pine64:~$ sudo pip3 install bigchaindb_driver
The directory '/home/ubuntu/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/ubuntu/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting bigchaindb_driver
  Downloading bigchaindb_driver-0.3.1.tar.gz (484kB)
    100% |████████████████████████████████| 491kB 564kB/s 
Requirement already satisfied: requests>=2.11.0 in /usr/local/lib/python3.5/dist-packages (from bigchaindb_driver)
Collecting bigchaindb~=1.0.0rc1 (from bigchaindb_driver)
  Downloading BigchainDB-1.0.0rc1.tar.gz (72kB)
    100% |████████████████████████████████| 81kB 1.4MB/s 
    Complete output from command python setup.py egg_info:
    zip_safe flag not set; analyzing archive contents...
    
    Installed /tmp/pip-build-9bje3497/bigchaindb/.eggs/pytest_runner-2.11.1-py3.5.egg
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-9bje3497/bigchaindb/setup.py", line 136, in <module>
        package_data={'bigchaindb.common.schema': ['*.yaml']},
      File "/usr/lib/python3.5/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/local/lib/python3.5/dist-packages/setuptools/dist.py", line 320, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/usr/local/lib/python3.5/dist-packages/setuptools/dist.py", line 377, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 852, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 1117, in best_match
        dist = working_set.find(req)
      File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 715, in find
        raise VersionConflict(dist, req)
    pkg_resources.VersionConflict: (PyNaCl 1.1.2 (/usr/local/lib/python3.5/dist-packages), Requirement.parse('PyNaCl~=1.0.1'))
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-9bje3497/bigchaindb/


```

**Comment by wputnam** [comment]
After updating to the latest bigchaindb (0.10.3) through pip, I was able to install bigchaindb_driver without any issue. This issue can probably be closed now.
