### ISSUE TITLE
v0.2.2 docs unreadable online and failing to build on ReadTheDocs

### ISSUE THREAD

**Issue by ttmc** [bigchaindb/bigchaindb-driver#304]
Here's a copy of the traceback from ReadTheDocs:

```text
Running Sphinx v1.5.3
making output directory...

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/bigchaindb-python-driver/envs/v0.2.2/lib/python3.5/site-packages/sphinx/cmdline.py", line 295, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/bigchaindb-python-driver/envs/v0.2.2/lib/python3.5/site-packages/sphinx/application.py", line 163, in __init__
    confoverrides or {}, self.tags)
  File "/home/docs/checkouts/readthedocs.org/user_builds/bigchaindb-python-driver/envs/v0.2.2/lib/python3.5/site-packages/sphinx/config.py", line 134, in __init__
    execfile_(filename, config)
  File "/home/docs/checkouts/readthedocs.org/user_builds/bigchaindb-python-driver/envs/v0.2.2/lib/python3.5/site-packages/sphinx/util/pycompat.py", line 129, in execfile_
    exec_(code, _globals)
  File "conf.py", line 15, in <module>
    import bigchaindb_driver
  File "/home/docs/checkouts/readthedocs.org/user_builds/bigchaindb-python-driver/checkouts/v0.2.2/bigchaindb_driver/__init__.py", line 1, in <module>
    from .driver import BigchainDB   # noqa
  File "/home/docs/checkouts/readthedocs.org/user_builds/bigchaindb-python-driver/checkouts/v0.2.2/bigchaindb_driver/driver.py", line 2, in <module>
    from .offchain import prepare_transaction, fulfill_transaction
  File "/home/docs/checkouts/readthedocs.org/user_builds/bigchaindb-python-driver/checkouts/v0.2.2/bigchaindb_driver/offchain.py", line 9, in <module>
    from bigchaindb.common.transaction import (
  File "/home/docs/checkouts/readthedocs.org/user_builds/bigchaindb-python-driver/envs/v0.2.2/lib/python3.5/site-packages/BigchainDB-0.10.2-py3.5.egg/bigchaindb/__init__.py", line 99, in <module>
    from bigchaindb.core import Bigchain  # noqa
  File "/home/docs/checkouts/readthedocs.org/user_builds/bigchaindb-python-driver/envs/v0.2.2/lib/python3.5/site-packages/BigchainDB-0.10.2-py3.5.egg/bigchaindb/core.py", line 7, in <module>
    from bigchaindb.common.transaction import TransactionLink
  File "/home/docs/checkouts/readthedocs.org/user_builds/bigchaindb-python-driver/envs/v0.2.2/lib/python3.5/site-packages/BigchainDB-0.10.2-py3.5.egg/bigchaindb/common/transaction.py", line 4, in <module>
    from cryptoconditions import (Fulfillment, ThresholdSha256Fulfillment,
ImportError: cannot import name 'ThresholdSha256Fulfillment'

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/bigchaindb-python-driver/envs/v0.2.2/lib/python3.5/site-packages/BigchainDB-0.10.2-py3.5.egg/bigchaindb/common/transaction.py", line 4, in <module>
    from cryptoconditions import (Fulfillment, ThresholdSha256Fulfillment,
ImportError: cannot import name 'ThresholdSha256Fulfillment'
The full traceback has been saved in /tmp/sphinx-err-9skq4nsr.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

More details of that failed build can be found at https://readthedocs.org/projects/bigchaindb-python-driver/builds/5619795/

**Comment by sbellem** [comment]
We'll need to do a release once https://github.com/bigchaindb/bigchaindb/issues/1602 is done.

**Comment by sbellem** [comment]
Was solved via https://github.com/bigchaindb/bigchaindb/releases/tag/v0.10.3
