### ISSUE TITLE
Is UPDATING bigchaindb possible?

### ISSUE THREAD

**Issue by Vasista-22** [bigchaindb/bigchaindb-driver#398]
* bigchaindb-driver version:0.4.1
* bigchaindb **server** version (`bigchaindb -v`):1.0.1
* Python version:3.5.2
* Operating System:ubuntu 16.04 LTS

### Description

I want to update bigchaindb to latest version
### What I Did

Do I have to install it anew or there is an option for updating the older version to a new one?

**Comment by codegeschrei** [comment]
Hey @Vasista-22 
I answered your comment here https://github.com/bigchaindb/bigchaindb-driver/issues/351#issuecomment-382255222

**Comment by Vasista-22** [comment]
I have updated bigchaindb on my system by following the commands specified in #351 
Then to start the bigchaindb I have executed the following:
          mongod --replSet=bigchain-rs
Then I opened a new terminal and did 
          bigchaindb -y configure mongodb
follwed by
          bigchaindb start

This is giving trouble.
vasista@vasista-OptiPlex-9020:~$ bigchaindb -y configure localmongodb
INFO:bigchaindb.config_utils:Configuration loaded from `/home/vasista/.bigchaindb`
Generating default configuration for backend localmongodb
Configuration written to /home/vasista/.bigchaindb
Ready to go!
vasista@vasista-OptiPlex-9020:~$ bigchaindb start
INFO:bigchaindb.config_utils:Configuration loaded from `/home/vasista/.bigchaindb`
[2018-04-20 12:22:15] [INFO] (bigchaindb.commands.bigchaindb) BigchainDB Version 2.0.0a1 (MainProcess - pid: 9443)
[2018-04-20 12:22:15] [INFO] (bigchaindb.commands.bigchaindb) Initializing database (MainProcess - pid: 9443)
[2018-04-20 12:22:15] [INFO] (bigchaindb.backend.mongodb.connection) Closing initial connection to MongoDB (MainProcess - pid: 9443)
[2018-04-20 12:22:15] [INFO] (bigchaindb.commands.bigchaindb) Starting BigchainDB main process. (MainProcess - pid: 9443)
Traceback (most recent call last):
  File "/usr/local/bin/bigchaindb", line 11, in <module>
    load_entry_point('BigchainDB==2.0.0a1', 'console_scripts', 'bigchaindb')()
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb/commands/bigchaindb.py", line 245, in main
    utils.start(create_parser(), sys.argv[1:], globals())
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb/commands/utils.py", line 160, in start
    return func(args)
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb/commands/utils.py", line 45, in configure
    command(args)
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb/commands/utils.py", line 72, in start_logging
    command(args)
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb/commands/bigchaindb.py", line 181, in run_start
    from bigchaindb.tendermint.commands import start
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb/tendermint/__init__.py", line 6, in <module>
    from bigchaindb.tendermint.lib import BigchainDB  # noqa
  File "/usr/local/lib/python3.5/dist-packages/bigchaindb/tendermint/lib.py", line 165
    f'''{utxo['transaction_id']}{utxo['output_index']}'''.encode()
                                                        ^
SyntaxError: invalid syntax


The process is not stopping.Also bigchaindb isn't starting
Please suggest a solution @codegeschrei

**Comment by codegeschrei** [comment]
Hey, can you please check the docs:
- [run the driver and BichainDB locally with docker](https://docs.bigchaindb.com/projects/py-driver/en/latest/quickstart.html#installation-guide-for-developers)
- [run BigchainDB locally](https://docs.bigchaindb.com/projects/contributing/en/latest/dev-setup-coding-and-contribution-process/run-node-as-processes.html)
- [run BigchainDB with docker](https://docs.bigchaindb.com/projects/contributing/en/latest/dev-setup-coding-and-contribution-process/run-node-with-docker-compose.html)

We don't run mongo with the `replica-set` option anymore.
If you want to read about the changes that came with the new version of BigchainDB I suggest these blogs:
- [BigchainDB 2.0 is Byzantine Fault Tolerant](https://blog.bigchaindb.com/bigchaindb-2-0-is-byzantine-fault-tolerant-5ffdac96bc44)
- [Some HTTP API Changes in the Next Release](https://blog.bigchaindb.com/some-http-api-changes-in-the-next-release-49612a537b0c)
- [Three Transaction Model Changes in the Next Release](https://blog.bigchaindb.com/three-transaction-model-changes-in-the-next-release-dadbac50094a)
- [Changes to the Server Command Line Interface in BigchainDB 2.0](https://blog.bigchaindb.com/changes-to-the-server-command-line-interface-in-bigchaindb-2-0-e1d6576e7155)

**Comment by codegeschrei** [comment]
Hey @Vasista-22 
I hope everything works for you know. I'm going to close this issue for now since it's been some time. Feel free to open it again if you still have problems.
