### ISSUE TITLE
Server installation and setup issue?

### ISSUE THREAD

**Issue by geoffroygivry** [bigchaindb/bigchaindb-driver#485]
* bigchaindb-driver version: 0.5.3
* bigchaindb **server** version (`bigchaindb -v`): 2.0.0b7
* Python version: 3.6
* Operating System: Ubuntu 18.04

### Description
Hi there! 
I think it is not really an issue, so apologies in advance for this, but I couldn't find any email for support.
I installed BigChainDB server in my local Ubuntu machine for testing purposes. I've followed strictly The page in the doc : How to Set Up a BigchainDB Network (http://docs.bigchaindb.com/projects/server/en/latest/simple-deployment-template/network-setup.html)
With no issues during the installation (note that I'm not an IT guy, I've never configure servers before).

The documentation (for me at least) was not clear about how to start BigChainDB, so 

### What I Did

```
bigchaindb start
```
and I got this:
```
INFO:bigchaindb.config_utils:Configuration loaded from `/home/geoff/.bigchaindb`
[2018-10-02 13:19:06] [INFO] (bigchaindb.commands.bigchaindb) BigchainDB Version 2.0.0b7 (MainProcess - pid: 4968)
[2018-10-02 13:19:06] [INFO] (bigchaindb.commands.bigchaindb) Initializing database (MainProcess - pid: 4968)
[2018-10-02 13:19:06] [INFO] (bigchaindb.backend.localmongodb.schema) Create database `bigchain`. (MainProcess - pid: 4968)
[2018-10-02 13:19:06] [INFO] (bigchaindb.backend.localmongodb.schema) Create `transactions` table. (MainProcess - pid: 4968)
[2018-10-02 13:19:06] [INFO] (bigchaindb.backend.localmongodb.schema) Collection transactions already exists. (MainProcess - pid: 4968)
[2018-10-02 13:19:06] [INFO] (bigchaindb.backend.localmongodb.schema) Ensure secondary indexes for `transactions`. (MainProcess - pid: 4968)
[2018-10-02 13:19:06] [INFO] (bigchaindb.backend.localmongodb.schema) Create `blocks` table. (MainProcess - pid: 4968)
[2018-10-02 13:19:06] [INFO] (bigchaindb.backend.localmongodb.schema) Collection blocks already exists. (MainProcess - pid: 4968)
[2018-10-02 13:19:06] [INFO] (bigchaindb.backend.localmongodb.schema) Ensure secondary indexes for `blocks`. (MainProcess - pid: 4968)
[2018-10-02 13:19:06] [INFO] (bigchaindb.backend.localmongodb.schema) Create `assets` table. (MainProcess - pid: 4968)
[2018-10-02 13:19:06] [INFO] (bigchaindb.backend.localmongodb.schema) Collection assets already exists. (MainProcess - pid: 4968)
[2018-10-02 13:19:06] [INFO] (bigchaindb.backend.localmongodb.schema) Ensure secondary indexes for `assets`. (MainProcess - pid: 4968)
[2018-10-02 13:19:06] [INFO] (bigchaindb.backend.localmongodb.schema) Create `metadata` table. (MainProcess - pid: 4968)
[2018-10-02 13:19:06] [INFO] (bigchaindb.backend.localmongodb.schema) Collection metadata already exists. (MainProcess - pid: 4968)
[2018-10-02 13:19:06] [INFO] (bigchaindb.backend.localmongodb.schema) Ensure secondary indexes for `metadata`. (MainProcess - pid: 4968)
[2018-10-02 13:19:06] [INFO] (bigchaindb.backend.localmongodb.schema) Create `validators` table. (MainProcess - pid: 4968)
[2018-10-02 13:19:06] [INFO] (bigchaindb.backend.localmongodb.schema) Collection validators already exists. (MainProcess - pid: 4968)[2018-10-02 13:19:06] [INFO] (bigchaindb.backend.localmongodb.schema) Ensure secondary indexes for `validators`. (MainProcess - pid: 4968)
[2018-10-02 13:19:06] [INFO] (bigchaindb.backend.localmongodb.schema) Create `elections` table. (MainProcess - pid: 4968)
[2018-10-02 13:19:06] [INFO] (bigchaindb.backend.localmongodb.schema) Collection elections already exists. (MainProcess - pid: 4968)
[2018-10-02 13:19:06] [INFO] (bigchaindb.backend.localmongodb.schema) Ensure secondary indexes for `elections`. (MainProcess - pid: 4968)
[2018-10-02 13:19:06] [INFO] (bigchaindb.backend.localmongodb.schema) Create `pre_commit` table. (MainProcess - pid: 4968)
[2018-10-02 13:19:06] [INFO] (bigchaindb.backend.localmongodb.schema) Collection pre_commit already exists. (MainProcess - pid: 4968)
[2018-10-02 13:19:06] [INFO] (bigchaindb.backend.localmongodb.schema) Ensure secondary indexes for `pre_commit`. (MainProcess - pid: 4968)
[2018-10-02 13:19:06] [INFO] (bigchaindb.backend.localmongodb.schema) Create `utxos` table. (MainProcess - pid: 4968)
[2018-10-02 13:19:06] [INFO] (bigchaindb.backend.localmongodb.schema) Collection utxos already exists. (MainProcess - pid: 4968)
[2018-10-02 13:19:06] [INFO] (bigchaindb.backend.localmongodb.schema) Ensure secondary indexes for `utxos`. (MainProcess - pid: 4968)
[2018-10-02 13:19:06] [INFO] (bigchaindb.backend.localmongodb.schema) Create `abci_chains` table. (MainProcess - pid: 4968)
[2018-10-02 13:19:06] [INFO] (bigchaindb.backend.localmongodb.schema) Collection abci_chains already exists. (MainProcess - pid: 4968)
[2018-10-02 13:19:06] [INFO] (bigchaindb.backend.localmongodb.schema) Ensure secondary indexes for `abci_chains`. (MainProcess - pid: 4968)
[2018-10-02 13:19:06] [INFO] (bigchaindb.commands.bigchaindb) Starting BigchainDB main process. (MainProcess - pid: 4968)
[2018-10-02 13:19:08] [INFO] (bigchaindb.start) Starting BigchainDB (MainProcess - pid: 4968)
[2018-10-02 13:19:08] [INFO] (bigchaindb.start)
****************************************************************************
*                                                                          *
*   ┏┓ ╻┏━╸┏━╸╻ ╻┏━┓╻┏┓╻╺┳┓┏┓    ┏━┓ ┏━┓ ╺┳┓┏━╸╻ ╻                         *
*   ┣┻┓┃┃╺┓┃  ┣━┫┣━┫┃┃┗┫ ┃┃┣┻┓   ┏━┛ ┃┃┃  ┃┃┣╸ ┃┏┛                         *
*   ┗━┛╹┗━┛┗━╸╹ ╹╹ ╹╹╹ ╹╺┻┛┗━┛   ┗━╸╹┗━┛╹╺┻┛┗━╸┗┛                          *
*   codename "fluffy cat"                                                  *
*   Initialization complete. BigchainDB Server is ready and waiting.       *
*                                                                          *
*   You can send HTTP requests via the HTTP API documented in the          *
*   BigchainDB Server docs at:                                             *
*    https://bigchaindb.com/http-api                                       *
*                                                                          *
*   Listening to client connections on: 0.0.0.0:9984                       *
*                                                                          *
****************************************************************************
 (MainProcess - pid: 4968)
[2018-10-02 13:19:08 +0100] [4980] [INFO] Starting gunicorn 19.9.0
[2018-10-02 13:19:08 +0100] [4980] [ERROR] Connection in use: ('0.0.0.0', 9984)
[2018-10-02 13:19:08 +0100] [4980] [ERROR] Retrying in 1 second.
[2018-10-02 13:19:09 +0100] [4980] [ERROR] Connection in use: ('0.0.0.0', 9984)
[2018-10-02 13:19:09 +0100] [4980] [ERROR] Retrying in 1 second.
Process bigchaindb_ws:
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/base_events.py", line 1045, in create_server
    sock.bind(sa)
OSError: [Errno 98] Address already in use

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.6/dist-packages/bigchaindb/utils.py", line 48, in run
    super().run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/bigchaindb/web/websocket_server.py", line 185, in start
    port=config['wsserver']['port'])
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/web.py", line 114, in run_app
    loop.run_until_complete(site.start())
  File "/usr/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/web_runner.py", line 89, in start
    reuse_port=self._reuse_port)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 1049, in create_server
    % (sa, err.strerror.lower()))
OSError: [Errno 98] error while attempting to bind on address ('0.0.0.0', 9984): address already in use
INFO      ABCIServer started on port: 26658
[2018-10-02 13:19:09] [INFO] (abci.app)  ABCIServer started on port: 26658 (MainProcess - pid: 4968)
[2018-10-02 13:19:10 +0100] [4980] [ERROR] Connection in use: ('0.0.0.0', 9984)
[2018-10-02 13:19:10 +0100] [4980] [ERROR] Retrying in 1 second.
[2018-10-02 13:19:11 +0100] [4980] [ERROR] Connection in use: ('0.0.0.0', 9984)
[2018-10-02 13:19:11 +0100] [4980] [ERROR] Retrying in 1 second.
[2018-10-02 13:19:12 +0100] [4980] [ERROR] Connection in use: ('0.0.0.0', 9984)
[2018-10-02 13:19:12 +0100] [4980] [ERROR] Retrying in 1 second.
[2018-10-02 13:19:13 +0100] [4980] [ERROR] Can't connect to ('0.0.0.0', 9984)
```
It looks like the setup is working and BigChainDB works as expected, 
when I type 
```
monit status 
```
it prints out that all the services are active and OK.

but when I go to :
http://hostname:9984
I've got a ERR_CONNECTION_REFUSED

Could someone please tell me what am I doing wrong ?
This is maybe super basic but I don't know how to go from there.
Many thanks in advance!

**Comment by geoffroygivry** [comment]
I've reproduced exactly the same steps on a AWS LightSail instance and it is working perfectly. So the issue is not on the installation process. Thank you.
