### ISSUE TITLE
Unable to install bigchaindb-driver package from pip

### ISSUE THREAD

**Issue by cclchd-lovishkumar** [bigchaindb/bigchaindb-driver#511]
bigchaindb-driver version: 0.6.2
bigchaindb version: 2
Python version: 3.10.1
Operating System: ubuntu 20.04

Description:
Wanted to setup the python bigchaindb-driver to create an asset using bigchaindb-driver in python

What I Did
I followed the installation steps using pip version 23 and python version 3.10.1, but when executed pip install bigchaindb-driver
getting error 
```
I executed
pip install -U bigchaindb-driver

getting

Defaulting to user installation because normal site-packages is not writeable
Collecting bigchaindb-driver
  Using cached bigchaindb_driver-0.6.2-py3-none-any.whl
Collecting pysha3~=1.0.2
  Using cached pysha3-1.0.2-cp310-cp310-linux_x86_64.whl
Collecting cryptoconditions==0.8.0
  Using cached cryptoconditions-0.8.0-py3-none-any.whl
Collecting python-rapidjson~=0.6.0
  Using cached python-rapidjson-0.6.3.tar.gz (189 kB)
  Preparing metadata (setup.py) ... done
Collecting python-rapidjson-schema==0.1.1
  Using cached python_rapidjson_schema-0.1.1-cp310-cp310-linux_x86_64.whl
Requirement already satisfied: requests>=2.20.0 in /usr/lib/python3/dist-packages (from bigchaindb-driver) (2.25.1)
Collecting base58~=1.0.0
  Using cached base58-1.0.3-py3-none-any.whl (3.1 kB)
Collecting cryptography~=2.3.1
  Using cached cryptography-2.3.1-cp34-abi3-manylinux1_x86_64.whl (2.1 MB)
Collecting PyNaCl~=1.1.0
  Using cached PyNaCl-1.1.2.tar.gz (3.1 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [39 lines of output]
      
      
              It is possible a package already installed in your system
              contains an version that is invalid according to PEP 440.
              You can try `pip install --use-pep517` as a workaround for this problem,
              or rely on a new virtual environment.
      
              If the problem refers to a package that is not installed yet,
              please contact that package's maintainers or distributors.
      
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-m7xv6b3q/pynacl_ce9c5558e32a422785260cb8e0224fa4/setup.py", line 187, in <module>
          setup(
        File "/home/lovish/.local/lib/python3.10/site-packages/setuptools/__init__.py", line 107, in setup
          _install_setup_requires(attrs)
        File "/home/lovish/.local/lib/python3.10/site-packages/setuptools/__init__.py", line 80, in _install_setup_requires
          _fetch_build_eggs(dist)
        File "/home/lovish/.local/lib/python3.10/site-packages/setuptools/__init__.py", line 85, in _fetch_build_eggs
          dist.fetch_build_eggs(dist.setup_requires)
        File "/home/lovish/.local/lib/python3.10/site-packages/setuptools/dist.py", line 879, in fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "/home/lovish/.local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 815, in resolve
          dist = self._resolve_dist(
        File "/home/lovish/.local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 844, in _resolve_dist
          env = Environment(self.entries)
        File "/home/lovish/.local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1044, in __init__
          self.scan(search_path)
        File "/home/lovish/.local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1077, in scan
          self.add(dist)
        File "/home/lovish/.local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1096, in add
          dists.sort(key=operator.attrgetter('hashcmp'), reverse=True)
        File "/home/lovish/.local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2631, in hashcmp
          self.parsed_version,
        File "/home/lovish/.local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2685, in parsed_version
          raise packaging.version.InvalidVersion(f"{str(ex)} {info}") from None
      pkg_resources.extern.packaging.version.InvalidVersion: Invalid version: '1.1build1' (package: distro-info)
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

```

**Comment by ttmc** [comment]
If you look at https://github.com/bigchaindb/bigchaindb-driver/graphs/contributors you might begin to get a sense of why things aren't working.

**Comment by r0m41q** [comment]
> If you look at https://github.com/bigchaindb/bigchaindb-driver/graphs/contributors you might begin to get a sense of why things aren't working.

Excuse me, but are you suggesting that the issue is due to the project not being maintained for four years?
