### ISSUE TITLE
docker-compose bdb-server service port clashes

### ISSUE THREAD

**Issue by sbellem** [bigchaindb/bigchaindb-driver#83]
* bigchaindb-driver version: `master` branch
* Python version: 3.5.2 (docker setup)
* Operating System: Ubuntu (docker setup)

### Description
In order to run the tests, one needs to run the BigchainDB server. When using docker-compose, one starts rethinkdb first, and then starts the bigchaindb server. The second operation resulted in an error.

### What I Did
Starting `bdb-server` with docker-compose.

```
$ docker-compose up -d bdb-server
Starting bigchaindbdriver_bdb-server_1

ERROR: for bdb-server  driver failed programming external connectivity on endpoint bigchaindbdriver_bdb-server_1 (c5aa4d5bee67dd8f943cfc49c6e6b3481cc666c6334d981d018b0bdc5e8ca12b): Bind for 0.0.0.0:32769 failed: port is already allocated
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "compose/cli/main.py", line 63, in main
AttributeError: 'ProjectError' object has no attribute 'msg'
docker-compose returned -1
```

**Comment by sbellem** [comment]
@sohkai coudl you say whether https://github.com/bigchaindb/bigchaindb-driver/commit/42b9210f7888892c114eee08a92339c66b0999bf#diff-4e5e90c6228fd48698d074241c2ba760R28 is really necessary?
